import React, { useState, useEffect } from 'react';
import { getMaintenance } from '../../services/api';
import { Wrench, ShieldAlert, CheckCircle, Clock, AlertTriangle, Send } from 'lucide-react';

export default function DispatchTerminal() {
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getMaintenance()
      .then(res => setOrders(res.data))
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  const handleResolve = (id) => {
    setOrders(prev => prev.map(o => o.id === id ? { ...o, status: 'DISPATCHED' } : o));
  };

  if (loading) {
    return (
      <div className="cockpit-panel" style={{ textAlign: 'center', padding: 40, fontFamily: 'var(--font-mono)' }}>
        SCANNING DISPATCH QUEUE...
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      {/* Top Status Header */}
      <div className="cockpit-panel" style={{ padding: '14px 20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.85rem', fontWeight: 700, color: 'var(--signal-cyan)' }}>
            AUTONOMOUS MAINTENANCE DISPATCH STRIP
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-mid)', marginTop: 2 }}>
            Real-time prioritized flight strips generated by anomaly detection and RUL threshold alarms
          </div>
        </div>

        <div style={{ display: 'flex', gap: 10 }}>
          <span className="hud-badge red">{orders.filter(o => o.priority === 'HIGH').length} HIGH SEVERITY</span>
          <span className="hud-badge amber">{orders.filter(o => o.priority === 'MEDIUM').length} SCHEDULED</span>
        </div>
      </div>

      {/* Flight Strips List */}
      <div>
        {orders.map((order) => {
          const priorityClass = (order.priority || 'LOW').toLowerCase();
          const isDispatched = order.status === 'DISPATCHED';

          return (
            <div key={order.id} className={`dispatch-strip ${priorityClass}`}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 16, flex: 1 }}>
                <div style={{ width: 100 }}>
                  <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.7rem', color: 'var(--text-dim)' }}>
                    {order.id}
                  </div>
                  <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.95rem', fontWeight: 700, color: 'var(--signal-cyan)' }}>
                    {order.machine_id}
                  </div>
                </div>

                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                    <span style={{ fontWeight: 600, color: 'var(--text-pure)', fontSize: '0.9rem' }}>
                      {order.title}
                    </span>
                    <span className={`hud-badge ${order.priority === 'HIGH' ? 'red' : order.priority === 'MEDIUM' ? 'amber' : 'mint'}`}>
                      {order.priority} PRIORITY
                    </span>
                  </div>
                  <div style={{ fontSize: '0.8rem', color: 'var(--text-mid)' }}>
                    {order.issue}
                  </div>
                  <div style={{
                    marginTop: 6,
                    padding: '4px 8px',
                    background: 'var(--bg-deck)',
                    borderLeft: '2px solid var(--signal-mint)',
                    borderRadius: 2,
                    fontSize: '0.75rem',
                    color: 'var(--signal-mint)',
                    fontFamily: 'var(--font-mono)'
                  }}>
                    ACTION: {order.recommended_action}
                  </div>
                </div>
              </div>

              {/* Action Button */}
              <div style={{ marginLeft: 20 }}>
                {isDispatched ? (
                  <span className="hud-badge mint" style={{ padding: '6px 12px' }}>
                    <CheckCircle size={12} style={{ marginRight: 4 }} /> DISPATCHED
                  </span>
                ) : (
                  <button
                    className="btn-hud"
                    style={{ background: 'var(--bg-panel-hover)', border: '1px solid var(--border-medium)' }}
                    onClick={() => handleResolve(order.id)}
                  >
                    <Send size={12} /> Dispatch Tech
                  </button>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
